name: Build and Deploy Documentation

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  SPHINXOPTS: --fail-on-warning --keep-going
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Prepare Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Python Requirements
        run: pip install -r requirements.txt
      - name: Build HTML Documentation
        run: make html
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/html'
  deploy:
    # Only run deploy on push events.  This will also trigger after a PR is
    # approved.  Sincet push will only trigger to the main branch, this will
    # only deploy the main branch.
    if: ${{ github.event_name == 'push' && github.repository == 'noaa-rdhpcs/noaa-rdhpcs.github.io' }}
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
