name: Build and Deploy Documentation

on: push

jobs:
  build:
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3
    - name: Prepare Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt
