name: reStructuredText Lint
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Prepare Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Python Requirements
        run: |
          pip install -r requirements.txt
          pip install doc8
      - name: Lint RST files
        run: doc8 source
